# Generated by Django 3.2.6 on 2021-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniName', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('Majors', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EditExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('months', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EditLin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteNam', models.CharField(max_length=30)),
                ('Urlo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EditProj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EditSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=20)),
            ],
        ),
    ]
